### ISSUE TITLE
Removing tasks from subfolders

### ISSUE THREAD

**Issue by tomlievesleymoe** [puppetlabs/puppetlabs-scheduled_task#213]
## Describe the Bug
When trying to remove tasks from a subfolder the subfolder is not seen. 
Debug output below.
`Debug: /Stage[main]/Base_moe/Scheduled_task[Symantec Endpoint Protection Error Analyzer]: Nothing to manage: no ensure and the resource doesn't exist`
Removing a task if not in a sub folder works as expected
## Expected Behavior
Task is removed from the subfolder in scheduled tasks.

## Steps to Reproduce
tried multiple variants of both the below.
`
scheduled_task { "Symantec Endpoint Protection\\Symantec Endpoint Protection Error Analyzer":
  ensure => 'absent',
  name   => 'Symantec Endpoint Protection\\Symantec Endpoint Protection Error Analyzer',
}`
`
scheduled_task { 'Symantec Endpoint Protection Error Analyzer':
        ensure      => absent,
        name        => 'Symantec Endpoint Protection Error Analyzer',
        provider    => 'taskscheduler_api2',
        working_dir => 'C:\\Windows\\System32\\Tasks\\Symantec Endpoint Protection'
      }
`
This works fine:
` scheduled_task { 'clear endpoint testing':
        ensure => absent,
        name   => 'clear cache',
      }`
     
## Environment
 - Puppet 6.19.1
 - scheduled_task 3.1.0
 - Platform Windows Server 2019

**Comment by LukasAud** [comment]
Hi @tomlievesleymoe, have you had the chance to try the adding the compatibility level just as @GSPatton suggested? Is it a valid fix for your issue?

Please let us know if this issue is still active.

**Comment by tomlievesleymoe** [comment]
> We've had a look at this and setting the compatibility level to 6 seems to have done the trick.
> 
> For example, this is the manifest we used
> 
> ```
> scheduled_task { "Symantec Endpoint Protection\\Symantec Endpoint Protection Error Analyzer": 
>   ensure => absent, 
>   name => "Symantec Endpoint Protection\\Symantec Endpoint Protection Error Analyzer", 
>   compatibility => 6, 
> }
> ```

Hi,

This worked, it was the compatibility flag level 6 that was required. i had tried it at a lower level and ruled it out.

Thanks for the help on this.
