### ISSUE TITLE
How to use disable_time_zone_synchronization

### ISSUE THREAD

**Issue by adriangalbincea** [puppetlabs/puppetlabs-scheduled_task#214]
Hi, I tried to put this option under the trigger with true or false value but it still does nothing to the task, the box will stay ticked on.

Can you please advise?

**Comment by LukasAud** [comment]
Hi @adriangalbincea, unfortunately I cannot give much advice if I don't have more information about the issue. Maybe our documentation can help you find some solution: 
https://github.com/puppetlabs/puppetlabs-scheduled_task#setup

If you still need help, we will need more details about the issue you are experiencing. Would you be able to provide us with some more information about the context of your issue? If you could give us some data such as the puppet manifest you are trying to run, the OS you are using it on and/or more details of the nature of the issue, we might be able to give you better advice.

**Comment by adriangalbincea** [comment]
Hi @LukasAud I found the resolution to this by mistake 3 days ago. Thanks for your reply

I had to add **'disable_time_zone_synchronization' => true** in trigger array

**Comment by LukasAud** [comment]
Hi @adriangalbincea, glad to hear your issue was fixed. Sorry we could not help you earlier, we have been busy. Thanks for sharing your findings, it may be helpful for future reference 👍
